version: '3.7'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: myMqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw

volumes:
  config:
  data:
  log:

networks:
  default:
    name: myMqtt-network