version: "3"
services:
  influxDB:
    container_name: inFluxDB
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./InfluxDB/InfluxDB:/var/lib/influxdb2
      - ./InfluxDB/config:/etc/influxdb
    restart: always
  telegraf:
    container_name: Telegraf
    image: telegraf:latest
    network_mode: "host"
    volumes:
      - ./Telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  grafana:
    container_name: Grafana
    image: grafana/grafana:latest
    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - ./Grafana:/var/lib/grafana
    links:
      - influxDB
    restart: always